### ISSUE TITLE
Make CSV separator configurable via settings file

### ISSUE THREAD

**Issue by dinkumoil** [Artem3213212/cuda_csv_hilite#1]
I would like to suggest an improvement to the plugin.

When I tried the plugin I've noticed that it always uses comma as CSV separators. It would be useful to have the ability to change that via the config file to e.g. semicolon.

**Comment by Alexey-T** [comment]
At Github we use pull requests. can you make Pullreq, please?

**Comment by Alexey-T** [comment]
You can "edit" file `__init__.py` on Github - this will make the Pullreq.
