### ISSUE TITLE
Please restore global plugin option "option_separator"

### ISSUE THREAD

**Issue by dinkumoil** [Artem3213212/cuda_csv_hilite#7]
IMO removing global option _option_separator_ was not a good idea. It requires setting a separator char everytime a _CSV_ document is loaded. Additionally the setting is not remembered across different _CudaText_ sessions.

I would like to suggest the following changes:

1. Store CSV separator setting to session file and also to the file meta data that is used in case option _ui_reopen_session_ is set to _false_.
2. Restore plugin option _option_separator_.
3. When loading a CSV file check if there exists some info concerning CSV separator for that file. If not, use the value of global plugin option _option_separator_.

**Comment by Alexey-T** [comment]
Maybe you could help to restore the option. (Git history shows how option was made).

**Comment by Alexey-T** [comment]
restored it. plugin updated.

**Comment by Alexey-T** [comment]
store option to session? not possible - Cud handles session save/load, plugin cannot change it. store separator to another file? possible. e.g. some ini file in settings dir. patch welcome. but this file will grow bigger and bigger. need to clean it sometimes.

**Comment by dinkumoil** [comment]
Thank you! I made a fix too, but you were faster.

**Comment by Alexey-T** [comment]
Reminder about toolbar configurer
